create table if not exists public.deal_observations (
  id bigint generated by default as identity primary key,
  source_engine text not null,
  origin text not null,
  destination text not null,
  destination_code text,
  airline text,
  price numeric,
  start_date date,
  end_date date,
  trip_length_bucket text not null default 'unknown',
  booking_link text,
  raw_payload jsonb,
  observed_at timestamptz not null default now()
);

create index if not exists deal_observations_origin_observed_at_idx
  on public.deal_observations (origin, observed_at desc);

create index if not exists deal_observations_route_profile_idx
  on public.deal_observations (origin, destination, trip_length_bucket, observed_at desc);

alter table public.deal_observations enable row level security;
